<?php


namespace app\models;
use yii\base\Model;

class BetsModel extends Model
{

    public $matchresult;
    public $phonenumber;
    public $moneybet;
    public function attributeLabels()
    {
        return [
            'matchresult' => 'Результат матча',
            'phonenumber' => 'Ваш номер телефона',
            'moneybet' => 'Сумма ставки',
        ]; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return[
            [['matchresult','phonenumber','moneybet'],'required', 'message' =>'Поле не может быть пустым'],
            //Дополнительные параметры
            [['moneybet'], 'integer','min' =>'100','max' => '1000']


        ] ;
    }
}