<?php


namespace app\models;
use yii\base\Model;

class BetsModel extends Model
{

    public $match_result;
    public $phone_number;
    public $money_bet;
    public function attributeLabels()
    {
        return [
            'match_result' => 'Результат матча',
            'phone_number' => 'Ваш номер телефона',
            'money_bet' => 'Сумма ставки',
        ]; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return[
            [['match_result','phone_number','money_bet'],'required', 'message' =>'Поле не может быть пустым'],
            //Дополнительные параметры
            [['money_bet'], 'integer','min' =>'100','max' => '1000']


        ] ;
    }
}