<?php

namespace app\models;

use yii\db\ActiveRecord;


class BetsForm extends ActiveRecord
{

    public static function tableName()
    {
        return 'bets'; // TODO: Change the autogenerated stub
    }
    //public $matchResult;
    //public $phoneNumber;
    //public $bet;

    public function attributeLabels()
    {
        return [
            'matchresult' => 'Результат матча',
            'phonenumber' => 'Ваш номер телефона',
            'moneybet' => 'Сумма ставки',
        ]; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return[
            [['matchresult','phonenumber','moneybet'],'required', 'message' =>'Поле не может быть пустым'],
                //Дополнительные параметры
            [['moneybet'], 'integer','min' =>'100','max' => '1000']


        ] ;
    }
}
